# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC
