# This provides us with GCC binary support so we can run bash
language: generic

sudo: required

script:
  - ./build.sh
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/aptRepoUpdater.sh; fi'

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"

notifications:
  slack: fossasia:3pMkQrSogvEMfnu9aJDW2ZYC

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      627301fd23568624540b108995c9610a1f772205
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      branch: master
